[Docs] Metrics
open-mmlab/mmocr pull request #1399
Opened 2022-09-21 04:31 UTC by xinke-wang

2022-09-23 06:51 UTC, gaotongxiao approved these changes

2022-09-23 06:51 UTC, gaotongxiao commented on docs/zh_cn/basic_concepts/evaluation.md
> +更多评测相关配置请参考评[测配置教程](../user_guides/config.md#评测配置)。
```suggestion
更多评测相关配置请参考[评测配置教程](../user_guides/config.md#评测配置)。
```

2022-09-23 06:51 UTC, gaotongxiao commented on docs/en/basic_concepts/evaluation.md
> +| [HmeanIOUMetric](mmocr.evaluation.metrics.hmean_iou_metric.HmeanIOUMetric)  | TextDet | `pred_polygons`<br>`pred_scores`<br>`gt_polygons` | `recall`<br>`precision`<br>`hmean`
invalid links

2022-09-23 06:51 UTC, gaotongxiao commented on docs/en/basic_concepts/evaluation.md
> +   - Filter out predictions with a score lower than `pred_score_thrs`
```suggestion
   - Filter out predictions with a score is lower than `pred_score_thrs`
```

2022-09-23 06:51 UTC, gaotongxiao commented on docs/en/basic_concepts/evaluation.md
> +# In addition, MMOCR also supports the combination evaluation of multiple metrics for the same task, such as using WordMetric and CharMetric at the same time
```suggestion
# In addition, MMOCR also supports the combined evaluation of multiple metrics for the same task, such as using WordMetric and CharMetric at the same time
```

2022-09-23 06:59 UTC, Harold-lkk commented on docs/zh_cn/basic_concepts/evaluation.md
> +   - 在数据处理阶段，`HmeanIOUMetric` 会计算并维护一个 {math}`M \times N` 的 IoU 矩阵 `iou_metric`，以方便后续的边界盒配对步骤。其中，M 和 N 分别为标签边界盒与预测边界盒的数量。由此，该矩阵的每个元素都存放了第 m 个标签边界盒与第 n 个预测边界盒之间的交并比（IoU）。
N is the filtered predictions

2022-09-23 07:01 UTC, Harold-lkk commented on docs/zh_cn/basic_concepts/evaluation.md
> +   我们建议面向学术研究的开发用户采用默认的 `vanilla` 匹配策略，以保证与其他论文的对比结果保持一致。而面向工业应用的开发用户则可以采用 `max_matching` 匹配策略，以获得更高的性能。
采用 `max_matching` 匹配策略，以获得更准确/精准/实际/真实的结果。

2022-09-23 08:55 UTC, gaotongxiao requested changes

2022-09-23 08:55 UTC, gaotongxiao commented on docs/en/basic_concepts/evaluation.md
> +Coming Soon!
Put the tutorials back to Evaluation in order to be consistent with OpenMMLab 2.0 conventions.

2022-09-26 06:10 UTC, gaotongxiao approved these changes

2022-09-26 06:11 UTC, merged