Ner task
open-mmlab/mmocr pull request #148
Opened 2021-05-01 14:23 UTC by HqWei

new version

2021-05-01 14:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/open-mmlab/mmocr?pullRequest=148) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/open-mmlab/mmocr?pullRequest=148) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/open-mmlab/mmocr?pullRequest=148) it.</sub>

2021-05-02 13:28 UTC, cuhk-hbsun commented on mmocr/models/ner/classifer/ner_classifier.py
> +    def extract_feat(self, imgs):
delete line26 -28

2021-05-02 13:28 UTC, cuhk-hbsun commented on mmocr/models/ner/classifer/ner_classifier.py
> +        return {'loss_cls': loss}
It's better to move this line to loss class, in other words, the return of loss class is a dict.

2021-05-02 13:28 UTC, cuhk-hbsun commented on mmocr/models/ner/convertors/ner_convertor.py
> +    """Convert between text, index and tensor for text recognize pipeline.
modify this docstring.

2021-05-02 13:28 UTC, cuhk-hbsun commented on mmocr/models/ner/convertors/ner_convertor.py
> +class NerConvertor:
Be careful to use the keyword `Ner`, unless all the ner methods using the same convertor.

2021-05-02 13:28 UTC, cuhk-hbsun commented on mmocr/models/ner/convertors/ner_convertor.py
> +    Args:
delete line8-9

2021-05-02 13:28 UTC, cuhk-hbsun commented on mmocr/models/ner/convertors/ner_convertor.py
> +        Returns:
update docstring

2021-05-02 13:28 UTC, cuhk-hbsun commented on mmocr/models/ner/convertors/ner_convertor.py
> +            ids (list): Corresponding IDs after conversion.
```suggestion
            input_ids (list): Corresponding ids after conversion.
```

2021-05-02 13:28 UTC, cuhk-hbsun commented on mmocr/models/ner/convertors/ner_convertor.py
> +            id2label (dict): Dict for mapping ID to label.
delete this line

2021-05-02 13:28 UTC, cuhk-hbsun commented on mmocr/models/ner/convertors/ner_convertor.py
> +        all_entities = []
```suggestion
        entities = []
```

2021-05-02 13:28 UTC, cuhk-hbsun commented on mmocr/models/ner/decoder/fc_decoder.py
> +        outputs = (logits, ) + outputs[
what's the meaning of line28-29?

2021-05-02 13:28 UTC, cuhk-hbsun commented on mmocr/models/ner/decoder/fc_decoder.py
> +        softmax = F.softmax(outputs[0], dim=2)
```suggestion
        softmax = F.softmax(logits, dim=2)
```

2021-05-02 13:28 UTC, cuhk-hbsun commented on mmocr/models/ner/encoder/bert_encoder.py
> +    """Ner encoder
Not `Ner encoder`

2021-05-02 13:28 UTC, cuhk-hbsun commented on mmocr/models/ner/encoder/bert_encoder.py
> +        output_attentions (bool):  Whether use the attentions in output
```suggestion
        output_attentions (bool):  Whether use the attentions in output.
```

2021-05-02 13:28 UTC, cuhk-hbsun commented on mmocr/models/ner/encoder/bert_encoder.py
> +        output_hidden_states (bool): Whether use the hidden_states in output
```suggestion
        output_hidden_states (bool): Whether use the hidden_states in output.
```

2021-05-02 13:28 UTC, cuhk-hbsun commented on mmocr/models/ner/encoder/bert_encoder.py
> +        hidden_act (str):  hidden layer activation
```suggestion
        hidden_act (str):  Hidden layer activation.
```

2021-05-02 13:28 UTC, cuhk-hbsun commented on mmocr/models/ner/loss/ner_loss.py
> +            loss_fct = FocalLoss(ignore_index=0)
What's the meaning of `fct`?

2021-05-02 13:28 UTC, cuhk-hbsun commented on tests/data/ner_toy_dataset/vocab_sample.txt
> +dscp we
Should be `d`?

2021-05-02 13:28 UTC, cuhk-hbsun commented on mmocr/core/evaluation/ner_metric.py
> +        origin: Original entities in groundtruth.
```suggestion
        origin (int): Number of original entities in groundtruth.
```

2021-05-02 13:28 UTC, cuhk-hbsun commented on mmocr/core/evaluation/ner_metric.py
> +        found: Predicted entities from model.
```suggestion
        found (int): Number of predicted entities from model.
```

2021-05-02 13:28 UTC, cuhk-hbsun commented on mmocr/core/evaluation/ner_metric.py
> +        right: Predicted entities that can match to the original annotation.
```suggestion
        right (int): Number of predicted entities that can match to the original annotation.
```

2021-05-02 13:28 UTC, cuhk-hbsun commented on mmocr/core/evaluation/ner_metric.py
> +        recall, precision, f1-score
```suggestion
        recall (float): Metric of recall.
        precision (float): Metric of precision.
        f1-score (float): Metric of f1-score.
```

2021-05-02 13:28 UTC, cuhk-hbsun commented on mmocr/core/evaluation/ner_metric.py
> +            'acc': round(precision, 4),
```suggestion
            'prec': round(precision, 4),
```

2021-05-02 13:28 UTC, cuhk-hbsun commented on mmocr/core/evaluation/ner_metric.py
> +        class_info (dict): precision,recall, f1-score in total and catogories.
```suggestion
        class_info (dict): Precision, recall, f1-score of total and each category.
```

2021-05-02 13:28 UTC, cuhk-hbsun commented on mmocr/datasets/ner_dataset.py
> +            ans: A dict.
Where is the ans?

2021-05-02 13:28 UTC, cuhk-hbsun commented on mmocr/models/common/losses/focal_loss.py
> +        input: [N, C]
update docstring.

2021-05-02 13:28 UTC, cuhk-hbsun commented on mmocr/models/ner/classifer/ner_classifier.py
> +    def aug_test(self, imgs, img_metas, **kwargs):
delete line43-54

2021-05-02 13:28 UTC, cuhk-hbsun commented on mmocr/models/ner/convertors/ner_convertor.py
> +            dict_type (str):
merge line21-29

2021-05-05 09:57 UTC, cuhk-hbsun requested changes

2021-05-05 09:57 UTC, cuhk-hbsun commented on mmocr/models/ner/convertors/ner_convertor.py
> +            for indx, tag in enumerate(results):
modify `indx` to `index` or `ind` in line135-160.

2021-05-07 06:25 UTC, cuhk-hbsun requested changes

2021-05-07 06:25 UTC, cuhk-hbsun commented on configs/ner/bert_softmax/README.md
> +| CLUENER2020 |     10748     |     10     |
Why entity_num is 10? Shouldn't be larger than text_num?

2021-05-07 06:25 UTC, cuhk-hbsun commented on configs/ner/bert_softmax/bert_softmax_cluener_18e.py
> +# optimizer
move line 5-10 to `configs/_base_/schedules/schedule_adadelta_18e.py`

2021-05-07 06:25 UTC, cuhk-hbsun commented on configs/ner/bert_softmax/bert_softmax_cluener_18e.py
> +checkpoint_config = dict(interval=1)
delete line 12-25 and use `_base_ = ['../../_base_/default_runtime.py']`

2021-05-07 06:25 UTC, cuhk-hbsun commented on configs/ner/bert_softmax/bert_softmax_cluener_18e.py
> +model = dict(
move line 92-114 to `configs/_base_/ner_models/bert_softmax.py`

2021-05-07 06:25 UTC, cuhk-hbsun commented on mmocr/core/evaluation/ner_metric.py
> +        class_info (dict): precision,recall, f1-score in total and catogories.
```suggestion
        class_info (dict): precision,recall, f1-score in total and each category.
```

2021-05-07 06:25 UTC, cuhk-hbsun commented on mmocr/core/evaluation/ner_metric.py
> +    for key in sorted(class_info.keys()):
delete line 83-90 and update total precision, recall and f1-score to class_info.

2021-05-07 06:25 UTC, cuhk-hbsun commented on mmocr/datasets/ner_dataset.py
> +        info = eval_ner(results, gt_infos)
```suggestion
       eval_results = eval_ner(results, gt_infos)
```

2021-05-07 06:25 UTC, cuhk-hbsun commented on mmocr/datasets/ner_dataset.py
> +        return info
```suggestion
        return eval_results
```

2021-05-07 06:25 UTC, cuhk-hbsun commented on mmocr/datasets/pipelines/ner_transforms.py
> +        ans = dict(
```suggestion
        results = dict(
```

2021-05-07 06:25 UTC, cuhk-hbsun commented on mmocr/datasets/pipelines/ner_transforms.py
> +        return ans
```suggestion
        return results
```

2021-05-07 06:25 UTC, cuhk-hbsun commented on mmocr/models/common/losses/focal_loss.py
> +        gamma (float): hyparam.
Be sure to use the capital form for the first character.

2021-05-07 06:25 UTC, cuhk-hbsun commented on mmocr/models/ner/encoder/bert_encoder.py
> +        hidden_act (str):  hidden layer activation.
```suggestion
        hidden_act (str):  Hidden layer activation.
```

2021-05-07 06:25 UTC, cuhk-hbsun commented on mmocr/models/ner/encoder/bert_encoder.py
> +        layer_norm_eps (float): eps.
```suggestion
        layer_norm_eps (float): Epsilon of layer norm.
```

2021-05-07 06:25 UTC, cuhk-hbsun commented on mmocr/models/ner/loss/ner_loss.py
> +    """The implementation the loss of named entity recognizier."""
```suggestion
    """The implementation the loss for named entity recognizier."""
```

2021-05-07 06:25 UTC, cuhk-hbsun commented on tests/data/ner_toy_dataset/eval_sample.json
> +{"text": "Congratulations to Tony for winning the championship in yesterday's competition.", "label": {"name": {"Tony": [[19, 23]]}}}
delete this file and use train_sample.json for both train and val.

2021-05-07 09:24 UTC, cuhk-hbsun requested changes

2021-05-07 09:24 UTC, cuhk-hbsun commented on mmocr/datasets/pipelines/ner_transforms.py
> +    def __call__(self, inputs):
rename to `results`

2021-05-07 09:24 UTC, cuhk-hbsun commented on mmocr/models/common/losses/focal_loss.py
> +        gamma (float): Hyparam.
Hyper-parameter.

2021-05-07 09:24 UTC, cuhk-hbsun commented on tools/test.py
> +            results = dataset.evaluate(outputs, **eval_kwargs)
Not make this change currently.

2021-05-08 09:28 UTC, cuhk-hbsun commented on configs/ner/bert_softmax/bert_softmax_cluener_18e.py
> +img_norm_cfg = dict(mean=[0.5, 0.5, 0.5], std=[0.5, 0.5, 0.5])
delete this line

2021-05-08 09:29 UTC, cuhk-hbsun commented on configs/ner/bert_softmax/bert_softmax_toy_dataset.py
> +img_norm_cfg = dict(mean=[0.5, 0.5, 0.5], std=[0.5, 0.5, 0.5])
delete this line

2021-05-08 09:30 UTC, cuhk-hbsun commented on mmocr/core/evaluation/ner_metric.py
> +        'f1': round(f1, 4)
```suggestion
        'f1-score': round(f1, 4)
```

2021-05-08 09:30 UTC, cuhk-hbsun commented on mmocr/datasets/ner_dataset.py
> +             'acc', 'recall', 'f1'.
```suggestion
             'acc', 'recall', 'f1-score'.
```

2021-05-08 09:31 UTC, cuhk-hbsun commented on mmocr/core/evaluation/ner_metric.py
> +            'f1': round(f1, 4)
```suggestion
            'f1-score': round(f1, 4)
```

2021-05-08 09:31 UTC, cuhk-hbsun commented on mmocr/models/common/losses/focal_loss.py
> +        gamma (float): Hyper-parameter..
```suggestion
        gamma (float): Hyper-parameter.
```

2021-05-08 09:32 UTC, cuhk-hbsun commented on mmocr/models/common/losses/focal_loss.py
> +        weight (float): Hyper-parameter..
```suggestion
        weight (float): Hyper-parameter.
```

2021-05-08 09:35 UTC, cuhk-hbsun commented on mmocr/models/ner/convertors/ner_convertor.py
> +    unknown_id = 100
move line14-16 to __init__ param and add docstring for these params.

2021-05-08 09:37 UTC, cuhk-hbsun commented on mmocr/models/ner/loss/ner_loss.py
> +            logits: [N, C]
```suggestion
            logits: Model output with shape [N, C].
```

2021-05-08 09:37 UTC, cuhk-hbsun commented on mmocr/models/ner/loss/ner_loss.py
> +
delete this line.

2021-05-12 02:16 UTC, innerlee commented on configs/ner/bert_softmax/README.md
> +|  trainset  | text_num | entity_num |
Add an empty line between title and table

2021-05-12 03:01 UTC, innerlee commented on configs/ner/bert_softmax/README.md
> +# Chinese Named Entity Recognition using BERT(softmax).
Chinese Named Entity Recognition using BERT + Softmax

2021-05-12 03:28 UTC, innerlee commented on docs/datasets.md
> +The structure of the named entity recognition dataset directory is organized as follows.
Add an empty line between title and content

2021-05-12 03:30 UTC, innerlee commented on docs/datasets.md
> +cluener_public
Change the style, similar to others

![image](https://user-images.githubusercontent.com/9464825/117914173-5bc11e00-b315-11eb-83fb-55c6f70a60e9.png)

2021-05-12 05:54 UTC, innerlee commented on mmocr/datasets/ner_dataset.py
> +    """
Add a line of descriptionn in the begininig

2021-05-12 05:56 UTC, innerlee commented on mmocr/core/evaluation/ner_metric.py
> +        gt_infos (list[dict]): Groudtruth infomation contains text and label .
Groudtruth infomation which contains text and label.

2021-05-12 06:41 UTC, innerlee commented on mmocr/core/evaluation/ner_metric.py
> +def compute(origin, found, right):
`_compute_f1`

2021-05-12 06:43 UTC, innerlee commented on mmocr/core/evaluation/ner_metric.py
> +def eval_ner(results, gt_infos):
`evaluate_ner_f1`

2021-05-12 06:51 UTC, innerlee commented on mmocr/core/evaluation/ner_metric.py
> +    print('lens: {} vs {}'.format(len(pred_entities), len(gt_entities)))
Use f-string

2021-05-12 06:52 UTC, innerlee commented on mmocr/core/evaluation/ner_metric.py
> +        'precision': round(precision, 4),
Remove the `round` function

2021-05-12 07:00 UTC, innerlee commented on mmocr/datasets/ner_dataset.py
> +        self.ann_file = ann_file
This line is not needed, since super class has done it

2021-05-12 07:01 UTC, innerlee commented on mmocr/datasets/ner_dataset.py
> +        self.ann_file = ann_file
Actually the whole `__init__` can be deleted

2021-05-12 07:37 UTC, innerlee commented on tools/train.py
> +        '--load-from', help='The checkpoint file to load from.')
This is typically set in configs. In most of the cases, using it directly means something wrong :)

2021-05-12 08:41 UTC, innerlee commented on mmocr/models/ner/utils/activations.py
> +def gelu(x):
What's the diffferece between these gelus and the one in pytorch?

2021-05-12 08:46 UTC, innerlee commented on mmocr/models/ner/utils/activations.py
> +def swish(x):
Is it this one? https://pytorch.org/docs/stable/generated/torch.nn.SiLU.html#silu

2021-05-12 08:48 UTC, innerlee commented on tests/data/ner_toy_dataset/train_sample.json
> +{"text": "Congratulations to Tony for winning the championship in yesterday's competition.", "label": {"name": {"Tony": [[19, 23]]}}}
Add newline to the end of the file

2021-05-12 08:49 UTC, innerlee commented on tests/test_models/test_ner_model.py
> +        # For IPython development when this __file__ is not defined
Is this necessary?

2021-05-12 11:29 UTC, innerlee commented on mmocr/models/ner/utils/activations.py
> +ACT2FN = {
As discussed offline, we will use existing pytorch functions if possible

2021-05-12 11:33 UTC, innerlee commented on mmocr/models/ner/loss/ner_loss.py
> +    def forward(self, logits, img_metas, device):
You can get the use the `logits.device`. No need to pass to it.

2021-05-12 11:41 UTC, innerlee commented on mmocr/models/ner/loss/ner_loss.py
> +class NerLoss(nn.Module):
I suggest split this loss to "MaskedFocalLoss/MaskedCrossEntropyLoss".

2021-05-12 11:42 UTC, innerlee commented on mmocr/models/ner/loss/ner_loss.py
> +        for i, _ in enumerate(img_metas):
L34-41 does not belong to the work of loss. It can be done in preprocessing

2021-05-14 10:59 UTC, innerlee commented on configs/ner/bert_softmax/README.md
> +# Chinese Named Entity Recognition using BERT + Softmax.
Remove the last period

2021-05-14 11:26 UTC, innerlee commented on demo/ner_demo.py
> +from mmocr.datasets import build_dataset  # noqa: F401
Can `# noqa: F401` be removed?

2021-05-14 11:27 UTC, innerlee commented on demo/ner_demo.py
> +                    print('{}: {}'.format(entity[0],
Use f-str format

2021-05-14 11:28 UTC, innerlee commented on demo/ner_demo.py
> +    assert len(result) == len([input_sentence])
Isn't `len([input_sentence])` always 1?

2021-05-14 11:30 UTC, innerlee commented on mmocr/apis/inference.py
> +    """Inference text(s) with the detector.
Is it a recognizor or detector?

2021-05-14 11:33 UTC, innerlee commented on mmocr/core/evaluation/ner_metric.py
> +            '%s' % key.replace('0_', ''),
Is this replacement universally applicable?

2021-05-14 11:34 UTC, innerlee commented on mmocr/core/evaluation/ner_metric.py
> +            '{:.3f}'.format(results[key]['precision']),
Use f-str

2021-05-14 11:35 UTC, innerlee commented on mmocr/core/evaluation/ner_metric.py
> +def show(results):
Rename to `_show_result`

2021-05-14 16:12 UTC, cuhk-hbsun commented on configs/ner/bert_softmax/bert_softmax_cluener_18e.py
> +img_prefix = ''
delete

2021-05-14 16:12 UTC, cuhk-hbsun commented on configs/ner/bert_softmax/bert_softmax_cluener_18e.py
> +    img_prefix=img_prefix,
delete

2021-05-14 16:12 UTC, cuhk-hbsun commented on configs/ner/bert_softmax/bert_softmax_cluener_18e.py
> +    img_prefix=img_prefix,
delete

2021-05-14 16:12 UTC, cuhk-hbsun commented on demo/ner_demo.py
> +from mmocr.datasets import build_dataset  # noqa: F401
```suggestion
from mmocr.datasets import build_dataset  # NOQA
```

2021-05-14 16:12 UTC, cuhk-hbsun commented on demo/ner_demo.py
> +from mmocr.models import build_detector  # noqa: F401
```suggestion
from mmocr.models import build_detector  # NOQA
```

2021-05-14 16:12 UTC, cuhk-hbsun commented on mmocr/apis/inference.py
> +        result (dict): Recognition results.
```suggestion
        result (dict): Predicted results.
```

2021-05-17 02:47 UTC, innerlee commented on configs/ner/bert_softmax/bert_softmax_cluener_18e.py
> +test_ann_file = 'data/cluener_public/dev.json'
Is the `_public` part of the dataset name?

2021-05-17 02:48 UTC, innerlee commented on configs/ner/bert_softmax/bert_softmax_cluener_18e.py
> +pretrained = 'checkpoints/bert_pretrain.pth'
We can provide an url in `pretrained`, so that users do not have to download them manually.

2021-05-17 03:21 UTC, innerlee commented on demo/ner_demo.py
> +                if entity[2] > len(text):
L34-35 should go before L33

2021-05-17 03:42 UTC, innerlee commented on mmocr/core/evaluation/ner_metric.py
> +            if result[1] < len(text):
As discussed in-person, this logic will be moved to post-processing

2021-05-17 03:46 UTC, innerlee commented on mmocr/datasets/ner_dataset.py
> +    def __init__(self, ann_file, loader, pipeline, test_mode=False):
The whole `__init__` can be removed since it is the same as `BaseDataset`

2021-05-17 03:50 UTC, innerlee commented on mmocr/datasets/ner_dataset.py
> +        gt_infos = []
Does this mean that

```python
gt_infos = list(self.data_infos)
```
?

2021-05-17 04:05 UTC, innerlee commented on mmocr/datasets/pipelines/ner_transforms.py
> +    """Ner transform ."""
Give a brief description on what transformation does this class handle

2021-05-17 04:06 UTC, innerlee commented on mmocr/datasets/pipelines/ner_transforms.py
> +    """Ner transform ."""
Also document the arguments in init

2021-05-17 04:06 UTC, innerlee commented on mmocr/datasets/pipelines/ner_transforms.py
> +        labels = self.label_convertor.conver_entity2label(
typo: conver

2021-05-17 04:11 UTC, innerlee commented on mmocr/datasets/pipelines/ner_transforms.py
> +        self.max_len = max_len
From L22, we know that `max_len` cannot be None right?

Either make an assertion that `max_len` is valid here, or make `max_len` a required positional argument without `=None`

2021-05-17 04:12 UTC, innerlee commented on mmocr/datasets/pipelines/ner_transforms.py
> +    def __init__(self):
This `__init__` can be removed

2021-05-17 04:13 UTC, innerlee commented on mmocr/datasets/pipelines/ner_transforms.py
> +            img=img_metas['img'],
What is the ` 'img' ` here?

2021-05-17 04:15 UTC, innerlee commented on mmocr/models/common/losses/focal_loss.py
> +        ignore index (int): Ignore index in label.
ignore_index

2021-05-17 04:16 UTC, innerlee commented on mmocr/models/common/losses/focal_loss.py
> +        gamma (float): Hyper-parameter.
Give a brief description of gamma, instead of a dummy text

2021-05-17 04:17 UTC, innerlee commented on mmocr/models/ner/classifer/ner_classifier.py
> +        return
If this is not implemented, then raise a NotImplementedError

2021-05-17 04:17 UTC, innerlee commented on mmocr/models/ner/classifer/ner_classifier.py
> +        pass
pass or not implemented?

2021-05-17 04:17 UTC, innerlee commented on mmocr/models/ner/classifer/ner_classifier.py
> +        pass
pass or not implemented?

2021-05-17 04:58 UTC, innerlee commented on mmocr/models/ner/loss/masked_focal_loss.py
> +    def __init__(self, num_labels=None, **kwargs):
Remove `**kwargs` if it is not used.

2021-05-17 04:59 UTC, innerlee commented on mmocr/models/ner/loss/masked_focal_loss.py
> +        self.criterion = FocalLoss(ignore_index=0)
Double check the hard-coded `ignore_index=0` is widely used in ner

2021-05-17 04:59 UTC, innerlee commented on mmocr/models/ner/loss/masked_focal_loss.py
> +    """The implementation of masked focal loss."""
Give a description on

* What is a masked focal loss, and
* Where the mask is defined

2021-05-17 05:00 UTC, innerlee commented on mmocr/models/ner/loss/masked_focal_loss.py
> +    """The implementation of masked focal loss."""
The current description does not give any useful info

2021-05-17 05:00 UTC, innerlee commented on mmocr/models/ner/loss/masked_focal_loss.py
> +                    - labels (list[int]): []*max_len
What is a `[]*max_len`?

2021-05-17 05:04 UTC, innerlee commented on mmocr/models/ner/utils/bert.py
> +                head_mask = head_mask.unsqueeze(0).unsqueeze(0).unsqueeze(
```python
head_mask = head_mask[None, None, :, None]
```

2021-05-17 05:05 UTC, innerlee commented on mmocr/models/ner/utils/bert.py
> +                head_mask = head_mask.unsqueeze(1).unsqueeze(-1).unsqueeze(-1)
```python
head_mask = head_mask[None, :, None, None]
```

2021-05-17 05:06 UTC, innerlee commented on mmocr/models/ner/utils/bert.py
> +                head_mask = head_mask.expand(self.num_hidden_layers, -1, -1,
I'm not sure if the `expand` is needed, since most operations support broadcasting

2021-05-17 05:10 UTC, innerlee commented on mmocr/models/ner/utils/bert.py
> +        extended_attention_mask = extended_attention_mask.to(
Get dtype in the begining and pass the dtype arguement to one_like and zeros_like

2021-05-17 05:12 UTC, innerlee commented on mmocr/models/ner/utils/bert.py
> +        extended_attention_mask = attention_masks.unsqueeze(1).unsqueeze(2)
Since `attention_masks` is not used in this function below, you can rename `extended_attention_mask` to `attention_mask`

2021-05-17 05:15 UTC, innerlee commented on mmocr/models/ner/utils/bert.py
> +        encoder_outputs = self.encoder(
```python
sequence_output, *encoder_outputs = self.encoder(...)
```

2021-05-17 05:18 UTC, innerlee commented on mmocr/models/ner/utils/bert.py
> +                 attention_probs_dropout_prob=0.1,
I don't understand the name `attention_probs_dropout_prob`. Why there are two probs?

2021-05-17 05:21 UTC, innerlee commented on mmocr/models/ner/convertors/ner_convertor.py
> +            raise NotImplementedError('Bioes format is not surpported now!')
now -> yet

typo surpported

2021-05-17 10:49 UTC, innerlee commented on mmocr/models/ner/classifer/ner_classifier.py
> +        assert label_convertor is not None
You can make encoder/decoder/loss/label_convertor positional arguments. And the four assersions can be removed.

2021-05-17 11:54 UTC, innerlee commented on configs/ner/bert_softmax/bert_softmax_cluener_18e.py
> +    'bert_softmax/bert_pretrain.pth.',
extra dot in the end

2021-05-18 01:54 UTC, innerlee commented on mmocr/models/ner/utils/bert.py
> +        # any TensorFlow checkpoint file
We do not have the burden of loading tf models. So LayerNorm -> layer_norm

2021-05-18 02:01 UTC, innerlee commented on configs/ner/bert_softmax/README.md
> +|   [bert_softmax](/configs/ner/bert_softmax/bert_softmax_cluener_18e.py)| [pretrain](https://download.openmmlab.com/mmocr/ner/bert_softmax/bert_pretrain.pth) |0.7885     |    0.7998 |  0.7941   |  [
Give a note on the source of pretrained model

2021-05-18 03:00 UTC, jeffreykuang approved these changes

2021-05-18 03:03 UTC, innerlee commented on demo/ner_demo.py
> +    # show the results
```python
    for pred_entities in result:
        for entity in pred_entities:
            print(f'{entity[0]}: {input_sentence[entity[1]:entity[2] + 1]}')

```

2021-05-18 03:33 UTC, cuhk-hbsun approved these changes

2021-05-18 03:33 UTC, merged

2023-04-07 10:26 UTC, OpenMMLab-Assistant-007 commented
Hi!
@HqWei 
First of all, we want to express our gratitude for your significant PR in the OpenMMLab project. Your contribution is highly appreciated, and we are grateful for your efforts in helping improve this open-source project during your personal time. We believe that many developers will benefit from your PR.

We would also like to invite you to join our Special Interest Group (SIG) private channel on Discord, where you can share your experiences, ideas, and build connections with like-minded peers. To join the SIG channel, simply message moderator— OpenMMLab on Discord or briefly share your open-source contributions in the #introductions channel and we will assist you. Look forward to seeing you there! Join us ：https://discord.gg/UjgXkPWNqA

If you have WeChat account，welcome to join our community on WeChat. You can add our assistant ：openmmlabwx. Please add "mmsig + Github ID" as a remark when adding friends：）
Thank you again for your contribution❤