Add kie image demo and docs.
open-mmlab/mmocr pull request #374
Opened 2021-07-18 11:01 UTC by manjrekarom

Added kie_image_demo.py file. It is inspired from ocr_image_demo.py and kie_test_imgs.py.
Docs are added in demo/docs/* and docs/getting_started.md

Resolves #312

2021-07-19 07:48 UTC, parulsingh23 commented
I have been trying to figure out how the KIE models work for a while, and your demo would be super helpful! However, I am having the following error when I try running the `!python demo/kie_image_demo.py demo/demo_kie.jpg demo/output.jpg` command with your code (on google colab):
```
Traceback (most recent call last):
  File "demo/kie_image_demo.py", line 333, in <module>
    main()
  File "demo/kie_image_demo.py", line 327, in main
    kie_model)
  File "demo/kie_image_demo.py", line 215, in det_recog_kie_inference
    kie_model, image, ann=ann_info, return_data=True)
  File "/content/mmocr/mmocr/apis/inference.py", line 138, in model_inference
    data = scatter(data, [device])[0]
  File "/usr/local/lib/python3.7/dist-packages/mmcv/parallel/scatter_gather.py", line 44, in scatter
    return scatter_map(inputs)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/parallel/scatter_gather.py", line 34, in scatter_map
    out = list(map(type(obj), zip(*map(scatter_map, obj.items()))))
  File "/usr/local/lib/python3.7/dist-packages/mmcv/parallel/scatter_gather.py", line 29, in scatter_map
    return list(zip(*map(scatter_map, obj)))
  File "/usr/local/lib/python3.7/dist-packages/mmcv/parallel/scatter_gather.py", line 27, in scatter_map
    return Scatter.forward(target_gpus, obj.data)
  File "/usr/local/lib/python3.7/dust-packages/mmcv/parallel/_functions.py", line 72, in forward
    streams = [_get_stream(device) for device in target_gpus]
  File "/usr/local/lib/python3.7/dist-packages/mmcv/parallel/_functions.py", line 72, in <listcomp>
    streams = [_get_stream(device) for device in target_gpus]
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/parallel/_functions.py", line 115, in _get_stream
    if _streams[device] is None:
TypeError: list indices must be integers or slices, not torch.device
```
Any suggestions on how I can fix this error would be greatly appreciated, thanks!

2021-07-20 09:03 UTC, gaotongxiao requested changes
Thanks for the contribution! I locally tested the script and got the same error as @parulsingh23. Could you double-check if the demo command works?

2021-07-20 09:09 UTC, manjrekarom commented
@parulsingh23 @gaotongxiao I think I know what this issue is. I was getting the same error and I think while trying to resolve I replaced device with device.index (after checking if instance is of torch.device). 

I will figure out a better way to resolve this issue.

2021-07-20 12:01 UTC, cuhk-hbsun commented on demo/kie_image_demo.py
> +def pad_text_indices(text_inds):
It will be better to use `mmocr/datasets/kie_dataset.py` directly, instead of copying these functions here.

2021-07-20 12:01 UTC, cuhk-hbsun commented on demo/kie_image_demo.py
> +def compute_relation(boxes, norm=10.):
same as above

2021-07-20 12:01 UTC, cuhk-hbsun commented on demo/kie_image_demo.py
> +def list_to_numpy(ann_infos, directed=False):
save as above

2021-07-20 12:01 UTC, cuhk-hbsun commented on demo/kie_image_demo.py
> +def parse_anno_info(annotations, vocab):
save as above

2021-07-21 05:00 UTC, adesgautam commented
Hi, I am getting this error running the file "tools/kie_test_imgs.py"
TypeError: SDMGR: __init__() got an unexpected keyword argument 'pretrained'

Earlier it was working. Can anybody tell how to resolve it ?

2021-07-21 05:10 UTC, gaotongxiao commented
@adesgautam Try deleting line 100:
```
cfg.model.pretrained = None
```
Let me know if that works. Thanks!

2021-07-21 05:22 UTC, adesgautam commented
Yup it works!!
Thank you @gaotongxiao

2021-07-26 08:51 UTC, parulsingh23 commented
Sorry, but I'm still not able to get 'demo/kie_image_demo.py' to work.

@adesgautam In what file are we supposed to locate `cfg.model.pretrained = None`, because even though I am running the 'demo/kie_image_demo.py' I have the exact same error message/callback as you. 

@manjrekarom Could you clarify in what file/what lines we are replacing device with device.index? And does this solve the issue of running 'demo/kie_image_demo.py' successfully?

Thanks!

2021-07-26 09:53 UTC, adesgautam commented
@parulsingh23 The line was in [tools/kie_test_imgs.py](https://github.com/open-mmlab/mmocr/blob/main/tools/kie_test_imgs.py)

Now it has been removed. Could you try tools/kie_test_imgs.py file for testing ?

2021-07-28 03:56 UTC, gaotongxiao commented
TODO: merge the script to ocr.py and change docs accordingly

2021-07-30 12:10 UTC, gaotongxiao commented
> TODO: merge the script to ocr.py and change docs accordingly

Done. **Note: the latest commits are developed based on #400. Therefore, this PR is intended to be reviewed and merged after merging #400 into main.** Otherwise the difference may be too much for reviewers.

2021-08-03 04:01 UTC, cuhk-hbsun commented on mmocr/datasets/kie_dataset.py
> +                'KIEDataset is only partially initialized'
```suggestion
                'KIEDataset is only initialized as a downstream demo task of text detection and recognition'
```

2021-08-04 06:19 UTC, cuhk-hbsun approved these changes

2021-08-04 06:20 UTC, merged