[Refactor] refactor recog dataset pipeline
open-mmlab/mmocr pull request #740
Opened 2022-01-19 07:09 UTC by cuhk-hbsun

1. Unify text recognize dataset pipeline, especially `test_pipeline`,  by
   1.1 replace `ToTensorOCR` and `NormalizeOCR` with `Normalize` and `DefaultFormatBundle`
   1.2 All test pipelines use `MultiRotateAugOCR` to give output with same format for different models.
2. Update test results with new pipeline.

**After PR**:

- [ ] Re-train one or some models (like `sar`) when available.

2022-01-28 12:02 UTC, gaotongxiao commented on mmocr/apis/test.py
> +        img_tensor = img_tensor.unsqueeze(0)
Would this affect MMDeploy? @AllentDan

2022-02-08 08:15 UTC, gaotongxiao reviewed
Please add more details in the PR message:
1. Motivation: Why should we use `MultiRotateAugOCR` in recognizer's pipelines
2. Deprecate warning for `ToTensorOCR` and `NormalizeOCR` (also include them int

Also need to figure out a way to automatically wrap recognizer's pipeline with `MultiRotateAugOCR` to avoid BC-breaking.

2022-02-09 01:41 UTC, AllentDan commented on mmocr/apis/test.py
> +        img_tensor = img_tensor.unsqueeze(0)
So far so good

2022-03-08 03:23 UTC, gaotongxiao requested changes
I don't quite understand the performance jitter under the new test pipeline. Could you leave some insights in the PR msg?

2022-03-08 03:23 UTC, gaotongxiao commented on mmocr/apis/utils.py
>  def disable_text_recog_aug_test(cfg, set_types=None):
It should be renamed since the propose of `update_pipeline_recog` has been changed

2022-03-08 03:23 UTC, gaotongxiao commented on tests/test_dataset/test_ocr_transforms.py
> +    assert results['img'].shape == (32, 100, 3)
A BC-breaking change. Need to document it in the PR msg.

2022-03-08 03:23 UTC, gaotongxiao commented on tests/test_dataset/test_test_time_aug.py
>      assert len(results['img_shape']) == 3
Duplicate assertion. Why is it changed?

2022-03-08 03:23 UTC, gaotongxiao commented on mmocr/apis/utils.py
>  def disable_text_recog_aug_test(cfg, set_types=None):
All config-related utils in this file should be moved to mmocr/utils/config.py. There are many duplicates.

2022-03-08 05:12 UTC, cuhk-hbsun commented on configs/_base_/recog_pipelines/seg_pipeline.py
> +    dict(type='CustomFormatBundle', keys=['gt_kernels']),
Not change but just remove default arguments of the class.

2022-03-08 05:19 UTC, cuhk-hbsun commented on tests/test_dataset/test_test_time_aug.py
>      assert len(results['img_shape']) == 3
Just a duplication

2022-03-08 09:57 UTC, cuhk-hbsun commented on mmocr/models/textrecog/recognizer/base.py
>              assert imgs[0].size(0) == 1, ('aug test does not support '
No, all recognizers can support batch inference. Only those setting `rotate_degree` multiple values cannot support batch inference.

2022-03-08 10:02 UTC, cuhk-hbsun commented on mmocr/__init__.py
> +mmdet_maximum_version = '3.0.0'
It has been modified by a previous pr, see [master code](https://github.com/open-mmlab/mmocr/blob/main/mmocr/__init__.py#L60)

2022-03-09 02:10 UTC, cuhk-hbsun commented on configs/_base_/recog_models/seg.py
> +        type='SegLoss', seg_downsample_ratio=1.0, seg_with_loss_weight=False),
It is not a modification but a mistake, after checking the original log file corresponding to the released model.

2022-03-14 02:01 UTC, gaotongxiao commented on mmocr/datasets/pipelines/ocr_transforms.py
> +                with type np.uint8 and value in 0-255.
Indentation and blank line

2022-03-14 11:55 UTC, cuhk-hbsun commented on tests/test_dataset/test_test_time_aug.py
> -    assert np.allclose([64, 32, 3], results['img_shape'])
conflict with line34

2022-03-22 02:47 UTC, gaotongxiao commented on mmocr/utils/config.py
> +                cfg[idx][1]['rotate_degrees'] = [0]
@AllentDan Merging this PR will move `disable_test_recog_aug_test` from `mmocr.apis.utils` to `mmocr.utils.config`, and this looks like a BC-breaking change to MMDeploy

2022-03-22 08:05 UTC, AllentDan commented on mmocr/utils/config.py
> +                cfg[idx][1]['rotate_degrees'] = [0]
We are not using this function in the MMDeploy codebase now. As for `tools/deployment/*` stuff, the fix can be done in this PR I guess by changing the `from mmocr.apis.inference import disable_text_recog_aug_test` to `from mmocr.utils.config import disable_text_recog_aug_test`

2022-03-22 08:06 UTC, AllentDan commented on mmocr/utils/config.py
> +                cfg[idx][1]['rotate_degrees'] = [0]
BTW, we are considering a PR warning deprecating deployment to MMOCR.

2022-03-22 08:08 UTC, gaotongxiao commented on mmocr/utils/config.py
> +                cfg[idx][1]['rotate_degrees'] = [0]
Sounds good

2022-03-31 07:17 UTC, gaotongxiao commented
Tests are still failing, we have to solve these issues before finally merging it.

2022-10-13 08:07 UTC, gaotongxiao commented
We will not introduce BC-breaking changes to 0.x version, but these efforts have been transferred to MMOCR 1.0 :)

2022-10-13 08:07 UTC, closed without merging