Add demo/README_zh.md
open-mmlab/mmocr pull request #802
Opened 2022-02-28 07:06 UTC by EighteenSprings

## Motivation

Add a simplified Chinese translation doc demo/README_zh.md to demo/README.md

## Modification

Translation only, nothing changed.

2022-02-28 07:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/open-mmlab/mmocr?pullRequest=802) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/open-mmlab/mmocr?pullRequest=802) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/open-mmlab/mmocr?pullRequest=802) it.</sub>

2022-02-28 08:52 UTC, BeyondYourself requested changes

2022-02-28 08:52 UTC, BeyondYourself commented on demo/README_zh.md
> +我们为了演示和应用，以 [ocr.py](https://github.com/open-mmlab/mmocr/blob/main/mmocr/utils/ocr.py) 脚本形式，提供了方便使用的 API。
1 建议中文翻译中把我们去了，我们这种适用于英文书写中
2 演示直接翻译为示例较为恰当
3 适当修正文本阅读通顺度

2022-02-28 08:52 UTC, BeyondYourself commented on demo/README_zh.md
> +该 API 可以通过命令行调用，也可以在另一个 python 脚本内调用。
此处的另一个指代什么

2022-02-28 08:52 UTC, BeyondYourself commented on demo/README_zh.md
> +**说明：** 使用 TextSnake 检测模型对图像上的文本执行检测推理，结果用 json 格式的文件（默认）导出，并保存可视化的文件。
说明翻译为 注更恰当

2022-02-28 08:52 UTC, BeyondYourself commented on demo/README_zh.md
> +- 命令行接口：
命令行接口不恰当吧，命令启动？？？

2022-02-28 08:52 UTC, BeyondYourself commented on demo/README_zh.md
> +- Python 接口：
python调用

2022-02-28 08:52 UTC, BeyondYourself commented on demo/README_zh.md
> +**说明：** 使用 CRNN_TPS 识别模型对文件夹下成百上千张图片进行批量识别推理。*批处理的尺寸设置为 10，以防内存溢出引起的 CUDA 运行时错误。*
1 说明 建议翻译为   注
2 “使用 CRNN_TPS 识别模型对文件夹下成百上千张图片进行批量识别推理” ，建议翻译为用CRNN_TPS对图片进行批量识别。不建议英文直译，太过生硬

2022-02-28 08:52 UTC, BeyondYourself commented on demo/README_zh.md
> +- 命令行接口：
此处修改和上述出现的类似

2022-02-28 08:52 UTC, BeyondYourself commented on demo/README_zh.md
> +- Python 接口：
此处修改和上述出现的类似

2022-02-28 08:52 UTC, BeyondYourself commented on demo/README_zh.md
> +**说明：** 使用 PANet_IC15（默认）检测模型和 SAR（默认）识别模型，对 demo/demo_text_det.jpg 图片执行 ocr（检测+识别）推理，在终端打印结果并展示可视化结果。
此处修改和上述出现的类似，适当调整中文阅读通顺度

2022-02-28 08:52 UTC, BeyondYourself commented on demo/README_zh.md
> +- Python 接口:
此处修改和上述出现的类似

2022-02-28 08:52 UTC, BeyondYourself commented on demo/README_zh.md
> +**说明：** 首先，使用 PS_CTW 检测模型和 SAR 识别模型，执行端到端 ocr （检测+识别）推理，然后对之前的结果使用 SDMGR 模型提取关键信息（KIE），并展示可视化结果。
此处修改和上述出现的类似

2022-02-28 08:52 UTC, BeyondYourself commented on demo/README_zh.md
> +- Python 接口：
此处修改和上述出现的类似

2022-02-28 08:52 UTC, BeyondYourself commented on demo/README_zh.md
> +用户能够通过指定 `det` 和/或 `recog` 参数的方式使用默认的预训练模型，，这种方式等同于指定 `*_config` 和 `*_ckpt` 对应参数。然而，手动指定 `*_config` 和 `*_ckpt` 的参数总会被 `det` 和/或 `recog` 的值覆盖。同样的规则也适用于 `kie`， `kie_config` 和 `kie_ckpt`。
手动指定 *_config 和 *_ckpt 的参数总会被 det 和/或 recog 的值覆盖。同样的规则也适用于 kie， kie_config 和 kie_ckpt。
修改为下面是否更通顺？
若手动设定*_config 和 *_ckpt等参数，则会被 det 和/或 recog 的值覆盖，同理kie， kie_config 和 kie_ckpt参数设定也一样

2022-02-28 08:52 UTC, BeyondYourself commented on demo/README_zh.md
> +| `img`               | str/list/tuple/np.array | **必需的** | 图像，文件夹路径，np array 或 list/tuple （包含图片路径或 np arrays） |
必需的不恰当

2022-02-28 08:52 UTC, BeyondYourself commented on demo/README_zh.md
> +| `output`           | str                     | None         | 输出结果可视化 - 图片路径或文件夹路径                  |
输出结果可视化
建议翻译为可视化结果输出

2022-02-28 08:52 UTC, BeyondYourself commented on demo/README_zh.md
> +[1]: 确保 模型兼容批处理模式。
去掉文字间的空格

2022-02-28 08:52 UTC, BeyondYourself commented on demo/README_zh.md
> +[2]: 只有 同时运行检测+识别模式，脚本才有效。
同上

2022-02-28 08:52 UTC, BeyondYourself commented on demo/README_zh.md
> +以上所有参数在命令行同样适用，您只需要在参数前简单添加两个连接符，并且将下参数中的下划线替换为连接符即可。
去掉人称代词

2022-02-28 08:52 UTC, BeyondYourself commented on demo/README_zh.md
> +| `merge`             | bool                    | False        | 是否对相邻框进行合并 [2]                              |
此处的[2]是什么意思，和上面的[1]指代不明确，英文中也存在这样的问题

2022-02-28 08:52 UTC, BeyondYourself commented on demo/README_zh.md
> +| `det_batch_size`    | int                     | 0            | 文本检测的批处理尺寸（设置为 0 则使用最大值）                         |
尺寸翻译为大小 ，对于Batch_size  括号中的简单说明为，若为0则表示使用最大值？？？此处的最大值是多少？？？有待说明

2022-02-28 08:52 UTC, BeyondYourself commented on demo/README_zh.md
> +| DB_r18        |            [链接](https://mmocr.readthedocs.io/en/latest/textdet_models.html#real-time-scene-text-detection-with-differentiable-binarization)            |         :x:          |
建议去掉参考这一列，将这一列与第一列进行合并

2022-02-28 08:52 UTC, BeyondYourself commented on demo/README_zh.md
> +| ------------- | :------------------------------------------------------------------------------------------------------------------------------------------------------: | :------------------: |
修改同上

2022-02-28 08:52 UTC, BeyondYourself commented on demo/README_zh.md
> +:::{提醒}
提醒翻译为 注

2022-02-28 08:52 UTC, BeyondYourself commented on demo/README_zh.md
> +SAR_CN 是唯一支持中文字符识别的模型，并且它需要一个中文字典。以便推理能成功运行，请先从 [这里](https://mmocr.readthedocs.io/en/latest/textrecog_models.html#chinese-dataset) 下载辞典。
SAR_CN 是唯一支持中文字符识别的模型有待更正 ，辞典翻译为字典

2022-02-28 08:52 UTC, BeyondYourself commented on demo/README_zh.md
> +## 附加
附加翻译为附是否更恰当

2022-02-28 08:52 UTC, BeyondYourself commented on demo/README_zh.md
> +- 执行检测+识别的推理（端到段 ocr），需要同时定义 `det` 和 `recog` 参数
端到端

2022-02-28 08:52 UTC, BeyondYourself commented on demo/README_zh.md
> +- `det_batch_size` 和 `recog_batch_size` 参数定义了你在同一时间想要传递给模型的图片数量。为了提高推理速度，应该尽可能设置你能设置的最大值。最大的批处理尺寸受模型复杂度和 GPU 的显存大小限制。
人称代词去掉，注意语句的通顺

2022-02-28 08:52 UTC, BeyondYourself commented on demo/README_zh.md
> +如果你对新特性有任何建议，请随时开一个主题，甚至可以一个 PR :)
翻译错误

2022-03-01 03:29 UTC, EighteenSprings commented
@BeyondYourself 谢谢建议，已修改，麻烦再审核下～～

2022-03-01 03:58 UTC, BeyondYourself requested changes
基本OK，修改完剩余的几个就可以了

2022-03-01 03:58 UTC, BeyondYourself commented on demo/README_zh.md
> +当用户从命令行执行脚本时，会默认配置文件都保存在 `configs/` 目录下。用户可以通过指定 `config_dir` 的值来自定义读取配置文件的文件夹。
文件默认保存在configs目录下，用户也可以设定通过设定config_dir来自定义配置文件读取

2022-03-01 03:58 UTC, BeyondYourself commented on demo/README_zh.md
> +对于布尔类型参数，将其置于命令中就会存储其值为真。
对于布尔类型参数，添加在命令中默认为true。

2022-03-01 03:58 UTC, BeyondYourself commented on demo/README_zh.md
> +:::{提醒}
提醒翻译为 注

2022-03-01 15:32 UTC, gaotongxiao commented on demo/README_zh.md
> +mmocr 为示例和应用，以 [ocr.py](https://github.com/open-mmlab/mmocr/blob/main/mmocr/utils/ocr.py) 脚本形式，提供了方便使用的 API。
```suggestion
MMOCR 为示例和应用，以 [ocr.py](https://github.com/open-mmlab/mmocr/blob/main/mmocr/utils/ocr.py) 脚本形式，提供了方便使用的 API。
```

2022-03-01 15:32 UTC, gaotongxiao commented on demo/README_zh.md
> +:::{注意}
```suggestion
:::{note}
```
This is a reserved keyword to render a note block on Readthedocs.

2022-03-01 15:32 UTC, gaotongxiao commented on demo/README_zh.md
> +:::{注意}
same

2022-03-01 15:32 UTC, gaotongxiao commented on demo/README_zh.md
> +:::{注意}
same

2022-03-01 15:32 UTC, gaotongxiao commented on demo/README_zh.md
> +:::{注意}
same

2022-03-02 01:35 UTC, EighteenSprings commented on demo/README_zh.md
> +:::{注意}
thanks, have fixed it  :)

2022-03-02 01:37 UTC, gaotongxiao reviewed
@EighteenSprings @BeyondYourself Thanks for your nice translation and review! It looks all good right now. Before merging, I'll be pushing a slight change to the script to ensure readthedocs can take this translation into account when generating Chinese documentation.

2022-03-02 01:46 UTC, gaotongxiao approved these changes

2022-03-02 01:51 UTC, merged

2023-04-04 09:26 UTC, OpenMMLab-gd commented
Hi @EighteenSprings！First of all, we want to express our gratitude for your significant PR in the MMOCR project. Your contribution is highly appreciated, and we are grateful for your efforts in helping improve this open-source project during your personal time. We believe that many developers will benefit from your PR.

We would also like to invite you to join our Special Interest Group (SIG) private channel on Discord, where you can share your experiences, ideas, and build connections with like-minded peers. To join the SIG channel, simply message moderator— OpenMMLab on Discord or briefly share your open-source contributions in the #introductions channel and we will assist you. Look forward to seeing you there! Join us ：https://discord.gg/UjgXkPWNqA

If you have WeChat account，welcome to join our community on WeChat. You can add our assistant ：openmmlabwx. Please add "mmsig + Github ID" as a remark when adding friends：）
Thank you again for your contribution❤ @EighteenSprings