[Update] Update the version requirement of mmdet in docker
open-mmlab/mmocr pull request #966
Opened 2022-04-23 03:44 UTC by Mountchicken

#965

2022-04-23 04:03 UTC, xinke-wang commented
I think we may also need to update the dependencies [here](https://mmocr.readthedocs.io/en/latest/install.html). The main branch requires a mmdet version >= 2.21. Also, there is a typo here, the `master` should be revised to `main` for our repo.

2022-04-23 04:46 UTC, xinke-wang approved these changes

2022-04-23 09:21 UTC, gaotongxiao requested changes

2022-04-23 09:21 UTC, gaotongxiao commented on docs/en/install.md
> +| 0.5.0        | 1.3.8 <= mmcv <= 1.5.0 | 2.21.0 <= mmdet <= 3.0.0  |
#944 was merged after the release of 0.5.0. 0.5.0 is still compatible with mmdet>=2.14.0

2022-04-23 09:21 UTC, gaotongxiao commented on docs/en/install.md
> +| 0.5.0        | 1.3.8 <= mmcv <= 1.5.0 | 2.21.0 <= mmdet <= 3.0.0  |
And there are extra spaces before "main"

2022-04-23 15:57 UTC, gaotongxiao reviewed
Forgot to mention a place needed to be changed as well: https://github.com/open-mmlab/mmocr/blob/main/mmocr/__init__.py#L59

2022-04-24 00:59 UTC, Mountchicken commented
> Forgot to mention a place needed to be changed as well: https://github.com/open-mmlab/mmocr/blob/main/mmocr/__init__.py#L59

Done

2022-04-24 02:12 UTC, gaotongxiao approved these changes

2022-04-24 02:12 UTC, merged